export const categories = [
  {
    name: 'Cashback',
    color: '#333',
    type: 'REVENUE',
    icon: 'Coins',
    mainCategory: true,
    subcategories: [],
  },
  {
    name: 'Investimento',
    color: '#333',
    type: 'REVENUE',
    icon: 'TrendingUp',
    mainCategory: true,
    subcategories: [
      {
        name: 'Rendimentos',
        color: '#333',
        type: 'REVENUE',
        mainSubcategory: true,
      },
      {
        name: 'Proventos',
        color: '#333',
        type: 'REVENUE',
        mainSubcategory: true,
      },
      {
        name: 'Juros',
        color: '#333',
        type: 'REVENUE',
        mainSubcategory: true,
      },
      {
        name: 'Resgate',
        color: '#333',
        type: 'REVENUE',
        mainSubcategory: true,
      },
    ],
  },
  {
    name: 'Outros (ganhos)',
    color: '#333',
    type: 'REVENUE',
    icon: 'Shuffle',
    mainCategory: true,
    subcategories: [],
  },
  {
    name: 'Prêmio',
    color: '#333',
    type: 'REVENUE',
    icon: 'Star',
    mainCategory: true,
    subcategories: [
      {
        name: 'Distribuição de Lucro',
        color: '#333',
        type: 'REVENUE',
        mainSubcategory: true,
      },
      {
        name: 'Bônus',
        color: '#333',
        type: 'REVENUE',
        mainSubcategory: true,
      },
    ],
  },
  {
    name: 'Presente',
    color: '#333',
    type: 'REVENUE',
    icon: 'Gift',
    mainCategory: true,
    subcategories: [],
  },
  {
    name: 'Receitas Variáveis',
    color: '#333',
    type: 'REVENUE',
    icon: 'HandCoins',
    mainCategory: true,
    subcategories: [
      {
        name: 'Restituição de Imposto',
        color: '#333',
        type: 'REVENUE',
        mainSubcategory: true,
      },
      {
        name: '13º Salário',
        color: '#333',
        type: 'REVENUE',
        mainSubcategory: true,
      },
      {
        name: 'Férias',
        color: '#333',
        type: 'REVENUE',
        mainSubcategory: true,
      },
      {
        name: 'Seguros',
        color: '#333',
        type: 'REVENUE',
        mainSubcategory: true,
      },
      {
        name: 'Reembolso',
        color: '#333',
        type: 'REVENUE',
        mainSubcategory: true,
      },
      {
        name: 'Comissões',
        color: '#333',
        type: 'REVENUE',
        mainSubcategory: true,
      },
      {
        name: 'Ajuda de custos',
        color: '#333',
        type: 'REVENUE',
        mainSubcategory: true,
      },
      {
        name: 'Empréstimos',
        color: '#333',
        type: 'REVENUE',
        mainSubcategory: true,
      },
      {
        name: 'Notas Fiscais emitidas',
        color: '#333',
        type: 'REVENUE',
        mainSubcategory: true,
      },
    ],
  },
  {
    name: 'Salário',
    color: '#333',
    type: 'REVENUE',
    icon: 'CircleDollarSign',
    mainCategory: true,
    subcategories: [
      {
        name: 'Salário',
        color: '#333',
        type: 'REVENUE',
        mainSubcategory: true,
      },
      {
        name: 'Pró-Labore',
        color: '#333',
        type: 'REVENUE',
        mainSubcategory: true,
      },
      {
        name: 'Aposentadoria',
        color: '#333',
        type: 'REVENUE',
        mainSubcategory: true,
      },
      {
        name: 'Benefício alimentação',
        color: '#333',
        type: 'REVENUE',
        mainSubcategory: true,
      },
      {
        name: 'Pensões',
        color: '#333',
        type: 'REVENUE',
        mainSubcategory: true,
      },
    ],
  },
  {
    name: 'Vendas',
    color: '#333',
    type: 'REVENUE',
    icon: 'Handshake',
    mainCategory: true,
    subcategories: [],
  },
  {
    name: 'Transferências',
    color: '#333',
    type: 'REVENUE',
    icon: 'ArrowRightLeft',
    mainCategory: true,
    subcategories: [
      {
        name: 'Resgate',
        color: '#333',
        type: 'REVENUE',
        mainSubcategory: true,
      },
      {
        name: 'Lançamento entre contas',
        color: '#333',
        type: 'REVENUE',
        mainSubcategory: true,
      },
    ],
  },
  /// //// Depesas
  {
    name: 'Alimentação',
    color: '#333',
    type: 'EXPENSE',
    icon: 'UtensilsCrossed',
    mainCategory: true,
    subcategories: [
      {
        name: 'Açougue',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Feira',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Padraia',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Restaurante',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Supermercado',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Cafeteria e Lanchonete',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Delivery',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Outros',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
    ],
  },
  {
    name: 'Assinaturas',
    color: '#333',
    type: 'EXPENSE',
    icon: 'Bell',
    mainCategory: true,
    subcategories: [
      {
        name: 'Assinaturas',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Jogos',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Música',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Streaming',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Televisão',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Telefone/Celular',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Outros',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
    ],
  },
  {
    name: 'Casa',
    color: '#333',
    type: 'EXPENSE',
    icon: 'House',
    mainCategory: true,
    subcategories: [
      {
        name: 'Água',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Aluguel/Prestação',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Condomínio',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Energia',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Funcionários',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Gás',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Internet',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'IPTU',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Lavandeira',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Manuteção',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Seguro',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Telefone/Celular',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Objetos de casa',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Outros',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
    ],
  },
  {
    name: 'Dívidas',
    color: '#333',
    type: 'EXPENSE',
    icon: 'CircleAlert',
    mainCategory: true,
    subcategories: [
      {
        name: 'Cartão de crédito em atraso',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Cheque especial',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Empréstimo',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Financiamento',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Tributos atrasados',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Outros',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
    ],
  },
  {
    name: 'Educação',
    color: '#333',
    type: 'EXPENSE',
    icon: 'GraduationCap',
    mainCategory: true,
    subcategories: [
      {
        name: 'Cursos',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Escola e faculdade',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Livros e materias',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Uniformes',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
    ],
  },
  {
    name: 'Empresarial',
    color: '#333',
    type: 'EXPENSE',
    icon: 'BriefcaseBusiness',
    mainCategory: true,
    subcategories: [
      {
        name: 'COFINS',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'CSLL',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Despesas Gerais Médias',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'INSS',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'IR',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'ISS',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Mensalidade Contador',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'PIS',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
    ],
  },
  {
    name: 'Lazer',
    color: '#333',
    type: 'EXPENSE',
    icon: 'TreePalm',
    mainCategory: true,
    subcategories: [
      {
        name: 'Bares',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Boates e festas',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Cinema',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Passeio',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Teatro',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Livrarias, jornais e revistas',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Jogos',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Brinquedos',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
    ],
  },
  {
    name: 'Objetivos de vida',
    color: '#333',
    type: 'EXPENSE',
    icon: 'Trophy',
    mainCategory: true,
    subcategories: [
      {
        name: 'Aposentadoria',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Metas pessoais',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
    ],
  },
  {
    name: 'Outros (gastos)',
    color: '#333',
    type: 'EXPENSE',
    icon: 'Shuffle',
    mainCategory: true,
    subcategories: [],
  },
  {
    name: 'Pessoal',
    color: '#333',
    type: 'EXPENSE',
    icon: 'User',
    mainCategory: true,
    subcategories: [
      {
        name: 'Cabelereiro',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Higiene pessoal',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Suguro de vida',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Academia',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Personal Trainer',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Acessórios',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Cosméticos',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Doações e dízimos',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Esportes',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Mesadas',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Pensões',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Presentes',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Seguros diversos',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Vestuário',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Outros',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
    ],
  },
  {
    name: 'Pet',
    color: '#333',
    type: 'EXPENSE',
    icon: 'PawPrint',
    mainCategory: true,
    subcategories: [
      {
        name: 'Alimentação',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Banho e tosa',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Medicamentos',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Veterinário',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Acessórios',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Outros',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
    ],
  },
  {
    name: 'Saúde',
    color: '#333',
    type: 'EXPENSE',
    icon: 'Stethoscope',
    mainCategory: true,
    subcategories: [
      {
        name: 'Academia',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Dentista',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Esportes',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Exames',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Farmácia',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Médico',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Plano de saúde',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Terapias',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Consultas e sessões',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
    ],
  },
  {
    name: 'Serviços',
    color: '#333',
    type: 'EXPENSE',
    icon: 'Wrench',
    mainCategory: true,
    subcategories: [
      {
        name: 'Advogados',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Manuteção e reparos',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Cartório/Correios',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
    ],
  },
  {
    name: 'Taxas',
    color: '#333',
    type: 'EXPENSE',
    icon: 'Receipt',
    mainCategory: true,
    subcategories: [
      {
        name: 'Anuidade cartão',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Carne leão',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'COFINS',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Gorjetas',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Imposto de renda',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'INSS',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'ISS',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'PIS',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Tarifa bancária',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Encargos',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
    ],
  },
  {
    name: 'Transferências',
    color: '#333',
    type: 'EXPENSE',
    icon: 'ArrowRightLeft',
    mainCategory: true,
    subcategories: [],
  },
  {
    name: 'Transporte',
    color: '#333',
    type: 'EXPENSE',
    icon: 'CarTaxiFront',
    mainCategory: true,
    subcategories: [
      {
        name: 'Combustivível',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Estacionamento',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Limpeza',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Manuteção',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Multas',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Pedágio',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Prestação',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Seguro',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Táxis e Aplicativos',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'IPVA',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Licenciamento',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Prestação/Aluguel',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
    ],
  },
  {
    name: 'Vestuário',
    color: '#333',
    type: 'EXPENSE',
    icon: 'Shirt',
    mainCategory: true,
    subcategories: [],
  },
  {
    name: 'Viagens',
    color: '#333',
    type: 'EXPENSE',
    icon: 'PlaneTakeoff',
    mainCategory: true,
    subcategories: [
      {
        name: 'Hospedagens',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Passagens',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
      {
        name: 'Passeios',
        color: '#333',
        type: 'EXPENSE',
        mainSubcategory: true,
      },
    ],
  },
  {
    name: 'Cartão de crédito',
    color: '#333',
    type: 'EXPENSE',
    icon: 'CreditCard',
    mainCategory: true,
    subcategories: [],
  },
] as const

// export const categories2 = {
//   Cashback: {
//     name: 'Cashback',
//     color: '#333',
//     type: 'REVENUE',
//     icon: 'Coins',
//     mainCategory: true,
//     subcategories: [],
//   },
//   Investimento: {
//     name: 'Investimento',
//     color: '#333',
//     type: 'REVENUE',
//     icon: 'TrendingUp',
//     mainCategory: true,
//     subcategories: {
//       Rendimentos: {
//         name: 'Rendimentos',
//         color: '#333',
//         type: 'REVENUE',
//         mainSubcategory: true,
//       },
//       Proventos: {
//         name: 'Proventos',
//         color: '#333',
//         type: 'REVENUE',
//         mainSubcategory: true,
//       },
//       Juros: {
//         name: 'Juros',
//         color: '#333',
//         type: 'REVENUE',
//         mainSubcategory: true,
//       },
//       Resgate: {
//         name: 'Resgate',
//         color: '#333',
//         type: 'REVENUE',
//         mainSubcategory: true,
//       },
//     },
//   },
//   'Outros (ganhos)': {
//     name: 'Outros (ganhos)',
//     color: '#333',
//     type: 'REVENUE',
//     icon: 'Shuffle',
//     mainCategory: true,
//     subcategories: [],
//   },
//   'Prêmio': {
//     name: 'Prêmio',
//     color: '#333',
//     type: 'REVENUE',
//     icon: 'Star',
//     mainCategory: true,
//     subcategories: {
//       'Distribuição de Lucro': {
//         name: 'Distribuição de Lucro',
//         color: '#333',
//         type: 'REVENUE',
//         mainSubcategory: true,
//       },
//       'Bônus': {
//         name: 'Bônus',
//         color: '#333',
//         type: 'REVENUE',
//         mainSubcategory: true,
//       },
//     }
//   },
//   'Presente': {
//     name: 'Presente',
//     color: '#333',
//     type: 'REVENUE',
//     icon: 'Gift',
//     mainCategory: true,
//     subcategories: [],
//   },
//   'Receitas Variáveis': {
//     name: 'Receitas Variáveis',
//     color: '#333',
//     type: 'REVENUE',
//     icon: 'HandCoins',
//     mainCategory: true,
//     subcategories: {
//        'Restituição de Imposto': {
//         name: 'Restituição de Imposto',
//         color: '#333',
//         type: 'REVENUE',
//         mainSubcategory: true,
//       },
//       '13º Salário': {
//         name: '13º Salário',
//         color: '#333',
//         type: 'REVENUE',
//         mainSubcategory: true,
//       },
//       'Férias': {
//         name: 'Férias',
//         color: '#333',
//         type: 'REVENUE',
//         mainSubcategory: true,
//       },
//       'Seguros': {
//         name: 'Seguros',
//         color: '#333',
//         type: 'REVENUE',
//         mainSubcategory: true,
//       },
//       'Reembolso': {
//         name: 'Reembolso',
//         color: '#333',
//         type: 'REVENUE',
//         mainSubcategory: true,
//       },
//       'Comissões': {
//         name: 'Comissões',
//         color: '#333',
//         type: 'REVENUE',
//         mainSubcategory: true,
//       },
//       'Ajuda de custos': {
//         name: 'Ajuda de custos',
//         color: '#333',
//         type: 'REVENUE',
//         mainSubcategory: true,
//       },
//       'Empréstimos': {
//         name: 'Empréstimos',
//         color: '#333',
//         type: 'REVENUE',
//         mainSubcategory: true,
//       },
//       'Notas Fiscais emitidas': {
//         name: 'Notas Fiscais emitidas',
//         color: '#333',
//         type: 'REVENUE',
//         mainSubcategory: true,
//       },
//     }
//   },
//   'Salário': {
//     name: 'Salário',
//     color: '#333',
//     type: 'REVENUE',
//     icon: 'CircleDollarSign',
//     mainCategory: true,
//     subcategories: {
//       'Salário': {
//         name: 'Salário',
//         color: '#333',
//         type: 'REVENUE',
//         mainSubcategory: true,
//       },
//       'Pró-Labore': {
//         name: 'Pró-Labore',
//         color: '#333',
//         type: 'REVENUE',
//         mainSubcategory: true,
//       },
//       'Aposentadoria': {
//         name: 'Aposentadoria',
//         color: '#333',
//         type: 'REVENUE',
//         mainSubcategory: true,
//       },
//       'Benefício alimentação': {
//         name: 'Benefício alimentação',
//         color: '#333',
//         type: 'REVENUE',
//         mainSubcategory: true,
//       },
//       'Pensões':{
//         name: 'Pensões',
//         color: '#333',
//         type: 'REVENUE',
//         mainSubcategory: true,
//       },
//     }
//   },
//   'Vendas': {
//     name: 'Vendas',
//     color: '#333',
//     type: 'REVENUE',
//     icon: 'Handshake',
//     mainCategory: true,
//     subcategories: {},
//   },
//   'Transferências': {
//   name: 'Transferências',
//   color: '#333',
//   type: 'REVENUE',
//   icon: 'ArrowRightLeft',
//   mainCategory: true,
//   subcategories: {
//     'Resgate': {
//       name: 'Resgate',
//       color: '#333',
//       type: 'REVENUE',
//       mainSubcategory: true,
//     },
//     'Lançamento entre contas': {
//       name: 'Lançamento entre contas',
//       color: '#333',
//       type: 'REVENUE',
//       mainSubcategory: true,
//     },
//   }
// },
//   /// //// Depesas
//   'Alimentação': {
//   name: 'Alimentação',
//   color: '#333',
//   type: 'EXPENSE',
//   icon: 'UtensilsCrossed',
//   mainCategory: true,
//   subcategories: {
//     'Açougue': {
//       name: 'Açougue',
//       color: '#333',
//       type: 'EXPENSE',
//       mainSubcategory: true,
//     },
//     'Feira': {
//       name: 'Feira',
//       color: '#333',
//       type: 'EXPENSE',
//       mainSubcategory: true,
//     },
//     'Padaria': {
//       name: 'Padaria',
//       color: '#333',
//       type: 'EXPENSE',
//       mainSubcategory: true,
//     },
//     'Restaurante': {
//       name: 'Restaurante',
//       color: '#333',
//       type: 'EXPENSE',
//       mainSubcategory: true,
//     },
//     'Supermercado': {
//       name: 'Supermercado',
//       color: '#333',
//       type: 'EXPENSE',
//       mainSubcategory: true,
//     },
//     'Cafeteria e Lanchonete': {
//       name: 'Cafeteria e Lanchonete',
//       color: '#333',
//       type: 'EXPENSE',
//       mainSubcategory: true,
//     },
//     'Delivery': {
//       name: 'Delivery',
//       color: '#333',
//       type: 'EXPENSE',
//       mainSubcategory: true,
//     },
//     'Outros': {
//       name: 'Outros',
//       color: '#333',
//       type: 'EXPENSE',
//       mainSubcategory: true,
//     },
//   }
// },

// 'Assinaturas': {
//   name: 'Assinaturas',
//   color: '#333',
//   type: 'EXPENSE',
//   icon: 'Bell',
//   mainCategory: true,
//   subcategories: {
//     'Assinaturas': {
//       name: 'Assinaturas',
//       color: '#333',
//       type: 'EXPENSE',
//       mainSubcategory: true,
//     },
//     'Jogos': {
//       name: 'Jogos',
//       color: '#333',
//       type: 'EXPENSE',
//       mainSubcategory: true,
//     },
//     'Música': {
//       name: 'Música',
//       color: '#333',
//       type: 'EXPENSE',
//       mainSubcategory: true,
//     },
//     'Streaming': {
//       name: 'Streaming',
//       color: '#333',
//       type: 'EXPENSE',
//       mainSubcategory: true,
//     },
//     'Televisão': {
//       name: 'Televisão',
//       color: '#333',
//       type: 'EXPENSE',
//       mainSubcategory: true,
//     },
//     'Telefone/Celular': {
//       name: 'Telefone/Celular',
//       color: '#333',
//       type: 'EXPENSE',
//       mainSubcategory: true,
//     },
//     'Outros': {
//       name: 'Outros',
//       color: '#333',
//       type: 'EXPENSE',
//       mainSubcategory: true,
//     },
//   }
// },

// 'Casa': {
//   name: 'Casa',
//   color: '#333',
//   type: 'EXPENSE',
//   icon: 'House',
//   mainCategory: true,
//   subcategories: {
//     'Água': {
//       name: 'Água',
//       color: '#333',
//       type: 'EXPENSE',
//       mainSubcategory: true,
//     },
//     'Aluguel/Prestação': {
//       name: 'Aluguel/Prestação',
//       color: '#333',
//       type: 'EXPENSE',
//       mainSubcategory: true,
//     },
//     'Condomínio': {
//       name: 'Condomínio',
//       color: '#333',
//       type: 'EXPENSE',
//       mainSubcategory: true,
//     },
//     'Energia': {
//       name: 'Energia',
//       color: '#333',
//       type: 'EXPENSE',
//       mainSubcategory: true,
//     },
//     'Funcionários': {
//       name: 'Funcionários',
//       color: '#333',
//       type: 'EXPENSE',
//       mainSubcategory: true,
//     },
//     'Gás': {
//       name: 'Gás',
//       color: '#333',
//       type: 'EXPENSE',
//       mainSubcategory: true,
//     },
//     'Internet': {
//       name: 'Internet',
//       color: '#333',
//       type: 'EXPENSE',
//       mainSubcategory: true,
//     },
//     'IPTU': {
//       name: 'IPTU',
//       color: '#333',
//       type: 'EXPENSE',
//       mainSubcategory: true,
//     },
//     'Lavanderia': {
//       name: 'Lavanderia',
//       color: '#333',
//       type: 'EXPENSE',
//       mainSubcategory: true,
//     },
//     'Manutenção': {
//       name: 'Manutenção',
//       color: '#333',
//       type: 'EXPENSE',
//       mainSubcategory: true,
//     },
//     'Seguro': {
//       name: 'Seguro',
//       color: '#333',
//       type: 'EXPENSE',
//       mainSubcategory: true,
//     },
//     'Telefone/Celular': {
//       name: 'Telefone/Celular',
//       color: '#333',
//       type: 'EXPENSE',
//       mainSubcategory: true,
//     },
//     'Objetos de casa': {
//       name: 'Objetos de casa',
//       color: '#333',
//       type: 'EXPENSE',
//       mainSubcategory: true,
//     },
//     'Outros': {
//       name: 'Outros',
//       color: '#333',
//       type: 'EXPENSE',
//       mainSubcategory: true,
//     },
//   }
// },
//   {
//     name: 'Dívidas',
//     color: '#333',
//     type: 'EXPENSE',
//     icon: 'CircleAlert',
//     mainCategory: true,
//     subcategories: [
//       {
//         name: 'Cartão de crédito em atraso',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//       {
//         name: 'Cheque especial',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//       {
//         name: 'Empréstimo',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//       {
//         name: 'Financiamento',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//       {
//         name: 'Tributos atrasados',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//       {
//         name: 'Outros',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//     ],
//   },
//   {
//     name: 'Educação',
//     color: '#333',
//     type: 'EXPENSE',
//     icon: 'GraduationCap',
//     mainCategory: true,
//     subcategories: [
//       {
//         name: 'Cursos',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//       {
//         name: 'Escola e faculdade',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//       {
//         name: 'Livros e materias',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//       {
//         name: 'Uniformes',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//     ],
//   },
//   {
//     name: 'Empresarial',
//     color: '#333',
//     type: 'EXPENSE',
//     icon: 'BriefcaseBusiness',
//     mainCategory: true,
//     subcategories: [
//       {
//         name: 'COFINS',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//       {
//         name: 'CSLL',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//       {
//         name: 'Despesas Gerais Médias',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//       {
//         name: 'INSS',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//       {
//         name: 'IR',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//       {
//         name: 'ISS',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//       {
//         name: 'Mensalidade Contador',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//       {
//         name: 'PIS',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//     ],
//   },
//   {
//     name: 'Lazer',
//     color: '#333',
//     type: 'EXPENSE',
//     icon: 'TreePalm',
//     mainCategory: true,
//     subcategories: [
//       {
//         name: 'Bares',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//       {
//         name: 'Boates e festas',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//       {
//         name: 'Cinema',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//       {
//         name: 'Passeio',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//       {
//         name: 'Teatro',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//       {
//         name: 'Livrarias, jornais e revistas',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//       {
//         name: 'Jogos',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//       {
//         name: 'Brinquedos',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//     ],
//   },
//   {
//     name: 'Objetivos de vida',
//     color: '#333',
//     type: 'EXPENSE',
//     icon: 'Trophy',
//     mainCategory: true,
//     subcategories: [
//       {
//         name: 'Aposentadoria',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//       {
//         name: 'Metas pessoais',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//     ],
//   },
//   {
//     name: 'Outros (gastos)',
//     color: '#333',
//     type: 'EXPENSE',
//     icon: 'Shuffle',
//     mainCategory: true,
//     subcategories: [],
//   },
//   {
//     name: 'Pessoal',
//     color: '#333',
//     type: 'EXPENSE',
//     icon: 'User',
//     mainCategory: true,
//     subcategories: [
//       {
//         name: 'Cabelereiro',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//       {
//         name: 'Higiene pessoal',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//       {
//         name: 'Suguro de vida',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//       {
//         name: 'Academia',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//       {
//         name: 'Personal Trainer',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//       {
//         name: 'Acessórios',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//       {
//         name: 'Cosméticos',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//       {
//         name: 'Doações e dízimos',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//       {
//         name: 'Esportes',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//       {
//         name: 'Mesadas',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//       {
//         name: 'Pensões',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//       {
//         name: 'Presentes',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//       {
//         name: 'Seguros diversos',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//       {
//         name: 'Vestuário',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//       {
//         name: 'Outros',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//     ],
//   },
//   {
//     name: 'Pet',
//     color: '#333',
//     type: 'EXPENSE',
//     icon: 'PawPrint',
//     mainCategory: true,
//     subcategories: [
//       {
//         name: 'Alimentação',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//       {
//         name: 'Banho e tosa',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//       {
//         name: 'Medicamentos',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//       {
//         name: 'Veterinário',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//       {
//         name: 'Acessórios',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//       {
//         name: 'Outros',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//     ],
//   },
//   {
//     name: 'Saúde',
//     color: '#333',
//     type: 'EXPENSE',
//     icon: 'Stethoscope',
//     mainCategory: true,
//     subcategories: [
//       {
//         name: 'Academia',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//       {
//         name: 'Dentista',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//       {
//         name: 'Esportes',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//       {
//         name: 'Exames',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//       {
//         name: 'Farmácia',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//       {
//         name: 'Médico',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//       {
//         name: 'Plano de saúde',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//       {
//         name: 'Terapias',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//       {
//         name: 'Consultas e sessões',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//     ],
//   },
//   {
//     name: 'Serviços',
//     color: '#333',
//     type: 'EXPENSE',
//     icon: 'Wrench',
//     mainCategory: true,
//     subcategories: [
//       {
//         name: 'Advogados',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//       {
//         name: 'Manuteção e reparos',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//       {
//         name: 'Cartório/Correios',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//     ],
//   },
//   {
//     name: 'Taxas',
//     color: '#333',
//     type: 'EXPENSE',
//     icon: 'Receipt',
//     mainCategory: true,
//     subcategories: [
//       {
//         name: 'Anuidade cartão',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//       {
//         name: 'Carne leão',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//       {
//         name: 'COFINS',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//       {
//         name: 'Gorjetas',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//       {
//         name: 'Imposto de renda',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//       {
//         name: 'INSS',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//       {
//         name: 'ISS',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//       {
//         name: 'PIS',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//       {
//         name: 'Tarifa bancária',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//       {
//         name: 'Encargos',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//     ],
//   },
//   {
//     name: 'Transferências',
//     color: '#333',
//     type: 'EXPENSE',
//     icon: 'ArrowRightLeft',
//     mainCategory: true,
//     subcategories: [],
//   },
//   {
//     name: 'Transporte',
//     color: '#333',
//     type: 'EXPENSE',
//     icon: 'CarTaxiFront',
//     mainCategory: true,
//     subcategories: [
//       {
//         name: 'Combustivível',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//       {
//         name: 'Estacionamento',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//       {
//         name: 'Limpeza',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//       {
//         name: 'Manuteção',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//       {
//         name: 'Multas',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//       {
//         name: 'Pedágio',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//       {
//         name: 'Prestação',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//       {
//         name: 'Seguro',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//       {
//         name: 'Táxis e Aplicativos',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//       {
//         name: 'IPVA',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//       {
//         name: 'Licenciamento',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//       {
//         name: 'Prestação/Aluguel',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//     ],
//   },
//   {
//     name: 'Vestuário',
//     color: '#333',
//     type: 'EXPENSE',
//     icon: 'Shirt',
//     mainCategory: true,
//     subcategories: [],
//   },
//   {
//     name: 'Viagens',
//     color: '#333',
//     type: 'EXPENSE',
//     icon: 'PlaneTakeoff',
//     mainCategory: true,
//     subcategories: [
//       {
//         name: 'Hospedagens',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//       {
//         name: 'Passagens',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//       {
//         name: 'Passeios',
//         color: '#333',
//         type: 'EXPENSE',
//         mainSubcategory: true,
//       },
//     ],
//   },
//  } as const
