export const banks = [
  {
    name: 'Banco do Brasil',
    imageUrl: 'https://main-banks.s3.amazonaws.com/bb.png',
    compe: '',
    ispb: '',
    main: true,
  },
  {
    name: 'Bradesco',
    imageUrl: 'https://main-banks.s3.amazonaws.com/bradesco.png',
    compe: '',
    ispb: '',
    main: true,
  },
  {
    name: 'BTG Pactual',
    imageUrl: 'https://main-banks.s3.amazonaws.com/btgpactual-1.png',
    compe: '',
    ispb: '',
    main: true,
  },
  {
    name: 'C6 Bank',
    imageUrl: 'https://main-banks.s3.amazonaws.com/c6bank-2.png',
    compe: '',
    ispb: '',
    main: true,
  },
  {
    name: 'Caixa',
    imageUrl: 'https://main-banks.s3.amazonaws.com/caixa.png',
    compe: '',
    ispb: '',
    main: true,
  },

  {
    name: 'Carteira',
    imageUrl: 'https://main-banks.s3.amazonaws.com/default.png',
    compe: '',
    ispb: '',
    main: true,
  },
  {
    name: 'Digio',
    imageUrl: 'https://main-banks.s3.amazonaws.com/digio.png',
    compe: '',
    ispb: '',
    main: true,
  },
  {
    name: 'Inter',
    imageUrl: 'https://main-banks.s3.amazonaws.com/intermedium.png',
    compe: '',
    ispb: '',
    main: true,
  },
  {
    name: 'Itaú',
    imageUrl: 'https://main-banks.s3.amazonaws.com/itau.png',
    compe: '',
    ispb: '',
    main: true,
  },
  {
    name: 'JP Morgan',
    imageUrl: 'https://main-banks.s3.amazonaws.com/jpmorgan.png',
    compe: '',
    ispb: '',
    main: true,
  },
  {
    name: 'Mercado Pago',
    imageUrl: 'https://main-banks.s3.amazonaws.com/mercadopago.png',
    compe: '',
    ispb: '',
    main: true,
  },
  {
    name: 'Neon',
    imageUrl: 'https://main-banks.s3.amazonaws.com/neon.png',
    compe: '',
    ispb: '',
    main: true,
  },
  {
    name: 'Next',
    imageUrl: 'https://main-banks.s3.amazonaws.com/next.png',
    compe: '',
    ispb: '',
    main: true,
  },
  {
    name: 'Nubank',
    imageUrl: 'https://main-banks.s3.amazonaws.com/nubank.png',
    compe: '',
    ispb: '',
    main: true,
  },
  {
    name: 'Nuconta',
    imageUrl: 'https://main-banks.s3.amazonaws.com/nuconta.png',
    compe: '',
    ispb: '',
    main: true,
  },
  {
    name: 'Nuinvest',
    imageUrl: 'https://main-banks.s3.amazonaws.com/nuinvest-1.png',
    compe: '',
    ispb: '',
    main: true,
  },
  {
    name: 'Original',
    imageUrl: 'https://main-banks.s3.amazonaws.com/original.png',
    compe: '',
    ispb: '',
    main: true,
  },
  {
    name: 'Pagbank',
    imageUrl: 'https://main-banks.s3.amazonaws.com/pagbank-1.png',
    compe: '',
    ispb: '',
    main: true,
  },
  {
    name: 'Pagseguro',
    imageUrl: 'https://main-banks.s3.amazonaws.com/pagseguro.png',
    compe: '',
    ispb: '',
    main: true,
  },
  {
    name: 'Paypal',
    imageUrl: 'https://main-banks.s3.amazonaws.com/paypal.png',
    compe: '',
    ispb: '',
    main: true,
  },
  {
    name: 'Picpay',
    imageUrl: 'https://main-banks.s3.amazonaws.com/picpay-1.png',
    compe: '',
    ispb: '',
    main: true,
  },
  {
    name: 'Safra',
    imageUrl: 'https://main-banks.s3.amazonaws.com/safra.png',
    compe: '',
    ispb: '',
    main: true,
  },
  {
    name: 'Santander',
    imageUrl: 'https://main-banks.s3.amazonaws.com/santander.png',
    compe: '',
    ispb: '',
    main: true,
  },
  {
    name: 'Sicoob',
    imageUrl: 'https://main-banks.s3.amazonaws.com/sicoob.png',
    compe: '',
    ispb: '',
    main: true,
  },
  {
    name: 'Outros',
    imageUrl: 'https://main-banks.s3.amazonaws.com/default.jpg',
    compe: '',
    ispb: '',
    main: true,
  },
]
